import type { Logger } from 'pino';
import type { CaptureService } from '../../modules/capture/capture.service.js';
import type { LibraryRepository } from '../../modules/library/library.repository.js';
import type { PracticeService } from '../../modules/practice/practice.service.js';
import type { DashboardService } from '../../modules/dashboard/dashboard.service.js';
import type { Pool } from 'pg';
import type { ReadingService } from '../../modules/reading/reading.service.js';
import type { SpeechService } from '../../modules/speech/speech.service.js';
import type { RateLimitContract } from '../middleware/rate-limit.js';
import type { ProfileServiceContract } from '../../modules/profile/profile.types.js';
import type { CoreAuthClient } from '../core/core-auth.client.js';
import type { WordPackRepository } from '../../modules/word-packs/word-packs.repository.js';
import type { WordPackStudyService } from '../../modules/word-packs/word-pack-study.service.js';
import type { PrivateLessonService } from '../../modules/private-lessons/private-lesson.service.js';
import type { CourseService } from '../../modules/courses/course.service.js';
import type { AddonAccessContract } from '../../modules/addons/addon-access.js';
import type { MinuteWallet } from '../../modules/private-lessons/minute-wallet.js';
import type { PostgresRealtimeCallGuard } from '../../modules/private-lessons/realtime-call-guard.js';
import type { NotificationService } from '../../modules/notifications/notification.service.js';

export type AppDependencies = {
  logger: Logger;
  checkDatabase: () => Promise<void>;
  coreAuthClient: CoreAuthClient;
  profileService: ProfileServiceContract;
  captureService?: CaptureService;
  libraryService?: LibraryRepository;
  practiceService?: PracticeService;
  dashboardService?: DashboardService;
  transferPool?: Pool;
  readingService?: ReadingService;
  speechService?: SpeechService;
  wordPackService?: WordPackRepository;
  wordPackStudyService?: WordPackStudyService;
  privateLessonService?: PrivateLessonService;
  courseService?: CourseService;
  addonAccess?: AddonAccessContract;
  minuteWallet?: MinuteWallet;
  realtimeCallGuard?: Pick<PostgresRealtimeCallGuard, 'connect' | 'end'>;
  enforceAddonEntitlements?: boolean;
  notificationService?: NotificationService;
  enforcePaidEntitlements?: boolean;
  corsOrigins?: string[];
  trustProxyHops?: number;
  rateLimiter?: RateLimitContract;
};
